"""SQLite database management for Leatt."""

from datetime import datetime
from pathlib import Path
from typing import Optional
from dataclasses import dataclass
from enum import Enum

from sqlalchemy import create_engine, Column, Integer, String, Float, DateTime, Boolean, Text
from sqlalchemy.orm import declarative_base, sessionmaker, Session

from .logger import get_logger

logger = get_logger("database")

Base = declarative_base()

_database: Optional["Database"] = None


class AlertSeverity(str, Enum):
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class ProcessRecord(Base):
    """Record of monitored processes."""
    __tablename__ = "processes"
    
    id = Column(Integer, primary_key=True)
    pid = Column(Integer, nullable=False)
    name = Column(String(255), nullable=False)
    path = Column(Text)
    user = Column(String(255))
    hash_sha256 = Column(String(64))
    first_seen = Column(DateTime, default=datetime.utcnow)
    last_seen = Column(DateTime, default=datetime.utcnow)
    is_trusted = Column(Boolean, default=False)
    risk_score = Column(Float, default=0.0)


class Alert(Base):
    """Security alerts generated by detection engines."""
    __tablename__ = "alerts"
    
    id = Column(Integer, primary_key=True)
    timestamp = Column(DateTime, default=datetime.utcnow)
    severity = Column(String(20), nullable=False)
    source = Column(String(50), nullable=False)
    process_name = Column(String(255))
    process_pid = Column(Integer)
    description = Column(Text, nullable=False)
    details = Column(Text)
    acknowledged = Column(Boolean, default=False)


class NetworkEvent(Base):
    """Network activity events."""
    __tablename__ = "network_events"
    
    id = Column(Integer, primary_key=True)
    timestamp = Column(DateTime, default=datetime.utcnow)
    process_pid = Column(Integer)
    process_name = Column(String(255))
    remote_address = Column(String(255))
    remote_port = Column(Integer)
    bytes_sent = Column(Integer, default=0)
    bytes_received = Column(Integer, default=0)
    connection_type = Column(String(10))


class FileEvent(Base):
    """File access events."""
    __tablename__ = "file_events"
    
    id = Column(Integer, primary_key=True)
    timestamp = Column(DateTime, default=datetime.utcnow)
    process_pid = Column(Integer)
    process_name = Column(String(255))
    file_path = Column(Text, nullable=False)
    event_type = Column(String(20), nullable=False)
    is_sensitive = Column(Boolean, default=False)


class TrustedProcess(Base):
    """Whitelist of trusted processes."""
    __tablename__ = "trusted_processes"
    
    id = Column(Integer, primary_key=True)
    name = Column(String(255), nullable=False)
    path = Column(Text)
    hash_sha256 = Column(String(64))
    publisher = Column(String(255))
    added_at = Column(DateTime, default=datetime.utcnow)
    added_by = Column(String(50), default="system")
    reason = Column(Text)


class Database:
    """Database connection and operations."""
    
    def __init__(self, db_path: Path):
        self.db_path = db_path
        db_path.parent.mkdir(parents=True, exist_ok=True)
        
        self.engine = create_engine(f"sqlite:///{db_path}", echo=False)
        Base.metadata.create_all(self.engine)
        
        self._session_factory = sessionmaker(bind=self.engine)
        logger.info(f"Database initialized at {db_path}")
    
    def get_session(self) -> Session:
        """Get a new database session."""
        return self._session_factory()
    
    def add_alert(
        self,
        severity: AlertSeverity,
        source: str,
        description: str,
        process_name: Optional[str] = None,
        process_pid: Optional[int] = None,
        details: Optional[str] = None,
    ) -> Alert:
        """Add a new alert to the database."""
        with self.get_session() as session:
            alert = Alert(
                severity=severity.value,
                source=source,
                description=description,
                process_name=process_name,
                process_pid=process_pid,
                details=details,
            )
            session.add(alert)
            session.commit()
            session.refresh(alert)
            logger.info(f"Alert added: [{severity.value}] {description}")
            return alert
    
    def add_process(
        self,
        pid: int,
        name: str,
        path: Optional[str] = None,
        user: Optional[str] = None,
        hash_sha256: Optional[str] = None,
    ) -> ProcessRecord:
        """Add or update a process record."""
        with self.get_session() as session:
            existing = session.query(ProcessRecord).filter_by(
                name=name, path=path
            ).first()
            
            if existing:
                existing.last_seen = datetime.utcnow()
                existing.pid = pid
                session.commit()
                return existing
            
            process = ProcessRecord(
                pid=pid,
                name=name,
                path=path,
                user=user,
                hash_sha256=hash_sha256,
            )
            session.add(process)
            session.commit()
            session.refresh(process)
            return process
    
    def add_network_event(
        self,
        process_pid: int,
        process_name: str,
        remote_address: str,
        remote_port: int,
        bytes_sent: int = 0,
        bytes_received: int = 0,
        connection_type: str = "tcp",
    ) -> NetworkEvent:
        """Record a network event."""
        with self.get_session() as session:
            event = NetworkEvent(
                process_pid=process_pid,
                process_name=process_name,
                remote_address=remote_address,
                remote_port=remote_port,
                bytes_sent=bytes_sent,
                bytes_received=bytes_received,
                connection_type=connection_type,
            )
            session.add(event)
            session.commit()
            return event
    
    def add_file_event(
        self,
        file_path: str,
        event_type: str,
        process_pid: Optional[int] = None,
        process_name: Optional[str] = None,
        is_sensitive: bool = False,
    ) -> FileEvent:
        """Record a file access event."""
        with self.get_session() as session:
            event = FileEvent(
                process_pid=process_pid,
                process_name=process_name,
                file_path=file_path,
                event_type=event_type,
                is_sensitive=is_sensitive,
            )
            session.add(event)
            session.commit()
            return event
    
    def is_process_trusted(self, name: str, path: Optional[str] = None, hash_sha256: Optional[str] = None) -> bool:
        """Check if a process is in the trusted whitelist."""
        with self.get_session() as session:
            query = session.query(TrustedProcess).filter_by(name=name)
            if path:
                query = query.filter_by(path=path)
            if hash_sha256:
                query = query.filter_by(hash_sha256=hash_sha256)
            return query.first() is not None
    
    def add_trusted_process(
        self,
        name: str,
        path: Optional[str] = None,
        hash_sha256: Optional[str] = None,
        publisher: Optional[str] = None,
        added_by: str = "user",
        reason: Optional[str] = None,
    ) -> TrustedProcess:
        """Add a process to the trusted whitelist."""
        with self.get_session() as session:
            trusted = TrustedProcess(
                name=name,
                path=path,
                hash_sha256=hash_sha256,
                publisher=publisher,
                added_by=added_by,
                reason=reason,
            )
            session.add(trusted)
            session.commit()
            session.refresh(trusted)
            logger.info(f"Process added to whitelist: {name}")
            return trusted
    
    def get_recent_alerts(self, limit: int = 50) -> list[Alert]:
        """Get recent alerts."""
        with self.get_session() as session:
            return session.query(Alert).order_by(
                Alert.timestamp.desc()
            ).limit(limit).all()
    
    def get_unacknowledged_alerts(self) -> list[Alert]:
        """Get all unacknowledged alerts."""
        with self.get_session() as session:
            return session.query(Alert).filter_by(
                acknowledged=False
            ).order_by(Alert.timestamp.desc()).all()


def get_database() -> Database:
    """Get the global database instance."""
    global _database
    if _database is None:
        db_path = Path(__file__).parent.parent.parent / "data" / "leatt.db"
        _database = Database(db_path)
    return _database
